### ISSUE TITLE
Attempts to mirror package with semantically equivalent version

### ISSUE THREAD

**Issue by pvandervelde** [themotleyfool/Klondike#90] opened 2015-06-17 04:35 UTC
I'm seeing a fair amount of the following errors in the klondike log. This seems to indicate that Klondike is trying to download the package from the mirror eventhough it exists in the local repository (it's a mirrored package in the first place). The 'alwaysCheckMirror' configuration is set to 'false' and the mirror is the standard nuget.org repository.

Using Klondike 2.0.0-beta.fe6acc3d

Not a problem at the moment but I could see it become an issue if we start hitting the repository more often.

    System.AggregateException: One or more errors occurred. ---> NuGet.Lucene.PackageOverwriteDeniedException: Package 'OpenCoverToCoberturaConverter' version '0.2.0.0' already exists.
       at NuGet.Lucene.LucenePackageRepository.<DownloadOrMoveOrAddPackageToFileSystemAsync>d__9.MoveNext() in c:\projects\nuget-lucene\source\NuGet.Lucene\LucenePackageRepository.cs:line 120
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at NuGet.Lucene.LucenePackageRepository.<AddPackageAsync>d__4.MoveNext() in c:\projects\nuget-lucene\source\NuGet.Lucene\LucenePackageRepository.cs:line 102
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NuGet.Lucene.LucenePackageRepository.<>c__DisplayClass25.<<AddPackage>b__24>d__27.MoveNext() in c:\projects\nuget-lucene\source\NuGet.Lucene\LucenePackageRepository.cs:line 230
       --- End of inner exception stack trace ---
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Threading.Tasks.Task.Wait()
       at NuGet.Lucene.LucenePackageRepository.AddPackage(IPackage package) in c:\projects\nuget-lucene\source\NuGet.Lucene\LucenePackageRepository.cs:line 231
       at NuGet.Lucene.Web.Models.DelegatingPackageRepository.AddPackage(IPackage package) in c:\projects\nuget-lucene\source\NuGet.Lucene.Web\Models\DelegatingPackageRepository.cs:line 62
       at NuGet.Lucene.Web.Models.MirroringPackageRepository.FindPackage(String packageId, SemanticVersion version) in c:\projects\nuget-lucene\source\NuGet.Lucene.Web\Models\MirroringPackageRepository.cs:line 90
       at NuGet.Lucene.Web.Controllers.PackagesODataController.Get(String id, String version) in c:\projects\nuget-lucene\source\NuGet.Lucene.Web\Controllers\PackagesODataController.cs:line 61
       at lambda_method(Closure , Object , Object[] )
       at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
       at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at NuGet.Lucene.Web.MessageHandlers.CrossOriginMessageHandler.<SendAsync>d__0.MoveNext() in c:\projects\nuget-lucene\source\NuGet.Lucene.Web\MessageHandlers\CrossOriginMessageHandler.cs:line 41
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()
    ---> (Inner Exception #0) NuGet.Lucene.PackageOverwriteDeniedException: Package 'OpenCoverToCoberturaConverter' version '0.2.0.0' already exists.
       at NuGet.Lucene.LucenePackageRepository.<DownloadOrMoveOrAddPackageToFileSystemAsync>d__9.MoveNext() in c:\projects\nuget-lucene\source\NuGet.Lucene\LucenePackageRepository.cs:line 120
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at NuGet.Lucene.LucenePackageRepository.<AddPackageAsync>d__4.MoveNext() in c:\projects\nuget-lucene\source\NuGet.Lucene\LucenePackageRepository.cs:line 102
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at NuGet.Lucene.LucenePackageRepository.<>c__DisplayClass25.<<AddPackage>b__24>d__27.MoveNext() in c:\projects\nuget-lucene\source\NuGet.Lucene\LucenePackageRepository.cs:line 230<---

**Comment by chriseldredge** [comment] 2015-06-29 18:07
The code that decides to attempt to mirror a package is in [MirroringPackageRepository.FindPackage](https://github.com/themotleyfool/NuGet.Lucene/blob/03df505c65fd8ca92686fd3f9fa793a88b7730f4/source/NuGet.Lucene.Web/Models/MirroringPackageRepository.cs#L77). The code will not attempt to mirror a package if the local repository can already find it.

It seems there is something strange going on where the package is already present in the local repository but it isn't being found by the FindPackage method.

I'm unable to reproduce this problem.

**Comment by chriseldredge** [comment] 2015-06-29 18:08
One issue I've seen in the past is that a package version like `0.2.0.0` and `0.2` are semantically equivalent, but perhaps Klondike does not always realize this.

Is it possible that a package with version `0.2` is already present but the client is attempting to obtain a version like `0.2.0.0`?

**Comment by pvandervelde** [comment] 2015-06-29 19:47
You're right on the money with that one. The logs say:

    MirroringPackageRepository FindPackage Mirroring package OpenCoverToCoberturaConverter 0.2.0 from http://www.nuget.org/api/v2/
    2015-06-12 16:05:44,347 ERROR  15 UnhandledExceptionLogger OnException One or more errors occurred.
    System.AggregateException: One or more errors occurred. ---> NuGet.Lucene.PackageOverwriteDeniedException: Package 'OpenCoverToCoberturaConverter' version '0.2.0.0' already exists.

The error makes sense now. I'm not sure if there is a fix for this but I'm not too fussed if there isn't.

**Comment by chriseldredge** [comment] 2015-06-29 20:42
Now that we know what is triggering the error, I can look at reproducing it and see if there's a simple fix.

**Comment by pvandervelde** [comment] 2015-06-30 01:43
Thanks. 

Just to add a bit more info. It looks like this might be caused by NuGet itself. The given package is on nuget.org as version 0.2.0 (https://www.nuget.org/packages/OpenCoverToCoberturaConverter/0.2.0) but when you pull it down the package version is 0.2.0.0.

**Comment by chriseldredge** [comment] 2015-06-30 15:56
This is fixed in https://github.com/themotleyfool/NuGet.Lucene/commit/fca5b32803c58f692f41a218202603ba2ce6b80c.

Need to update Klondike to use that build before it'll be fixed here.

**Comment by chriseldredge** [comment] 2015-07-14 16:53
Fixed in 536061c7.

**Closed** 2015-07-14 16:53 UTC
Labels: bug
