### ISSUE TITLE
Visual Studio 2012 NuGet Package Manager shows status code 400 instead of list of packages

### ISSUE THREAD

**Issue by gsommerw** [themotleyfool/Klondike#98] opened 2015-07-23 08:24 UTC
Hello,

I configured package source Klondike with Url http://servername:8082/api in the NuGet Package Manager Settings, but instead of a list of packages from the NuGet Gallery, I get status code 400 Bad Request.

Klondike is running self hosted and listening on Port 8082 and I can use the Api, though nothing is found, when I query i.e. Package NUnit form NuGet Gallery

<add key="packageMirrorTargetUrl" value="http://www.nuget.org/api/v2/" />

is configured in Settings.config. When using the NuGet Gallery directly or via Sonatype Nexus or ProGet the URL https://www.nuget.org/api/v2/ works, but when I use https instead of http in Klondike I still get status 400.

Is this a bug or am I doing something wrong?

Best Regards,
Gerhard

**Comment by chriseldredge** [comment] 2015-07-23 13:40
When you browse to http://servername:8082/ does the page footer show that there are packages in your repository? Can you browse the Packages link in the top navigation and see a list of packages?

You can also check the log in Klondike's App_Data/Logs/Klondike.log and see if there are any errors or other hints that may indicate the problem.

**Comment by gsommerw** [comment] 2015-07-24 06:26
There are 0 packages, but I thought, that is the count of my own packages, that I uploaded. And there are none at the time.

There is no Logs directory in App_Data, only Lucene and Packages.

**Comment by gsommerw** [comment] 2015-07-24 12:21
I am behind a proxy. Might this be the cause?

**Comment by chriseldredge** [comment] 2015-07-24 13:51
Klondike will mirror packages if you use it as a package source when installing a package or restoring packages. Searching Klondike will not return search results from a mirrored repository though. It will only show packages that are already included in its own repository.

**Comment by gsommerw** [comment] 2015-07-24 14:22
I use it as a package source in Visual Studio. There I get the status code 400 and no packages are listed.

**Comment by chriseldredge** [comment] 2015-07-24 14:26
You said earlier that you have zero packages. I'm not sure why you are getting a 400 Bad Request when you try to search, but until you have at least one package in Klondike the search results would always be empty regardless.

Since there is no Logs directory under App_Data, I wonder if there is a problem with permissions or some other configuration issue with the identity of the app pool that runs Klondike. There should be a log file that at least indicates the app has started up and is ready to work.

**Comment by gsommerw** [comment] 2015-07-27 05:48
I am running it as a windows service, but I will try it in IIS next. Maybe it is only a problem with the self-hosted version.

**Comment by chriseldredge** [comment] 2015-08-05 18:04
You can also try running the self-hosted program in a command prompt and see if any errors appear on the console.

I just tested Klondike with Visual Studio 2012 and it seems to work for me. I'm closing this issue but if you can provide more specific details on how to reproduce a 400 Bad Request feel free to reopen the issue.

**Closed by chriseldredge** 2015-08-05 18:04 UTC
Labels: question
