### ISSUE TITLE
VS 2015 Update 2 doesn't work with Klondike

### ISSUE THREAD

**Issue by kwchapman** [themotleyfool/Klondike#143] opened 2016-04-01 00:19 UTC
Before VS 2015 Update 2 NuGet would first issue a Get request to /api which gave Klondike a chance to issue a 307 redirect to /api/odata.

With VS 2015 Update 2 installed the initial NuGet request is a request for a package like api/Packages(Id='Autofac',Version='3.5.2'). Klondike then returns a 404 so the NuGet client never gets redirected to the /api/odata endpoint.

**Comment by CasperTDK** [comment] 2016-04-01 07:36
+1

**Comment by alex-parfenyuk** [comment] 2016-04-01 09:24
+1

**Comment by mortenn** [comment] 2016-04-01 12:39
This can probably be worked around with a url rewrite rule in IIS.

**Comment by TimBo93** [comment] 2016-04-01 20:55
NuGet sucks +1

**Comment by lukeskinner** [comment] 2016-04-01 23:11
What does your URL format look like in the package manager settings?

Using the following URL format worked for me: ```http://localhost:8080/api/odata```.

I'm using Visual Studio 2015 Community Update 2 with the 3.4.1.807 NuGet Package Manager installed.

The first request went straight to ```http://localhost:8080/api/odata/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework='net45'&includePrerelease=true&$skip=0&$top=26```

It then proceeded to query each package returned in the first request using ```http://localhost:8080/api/odata/FindPackagesById()?Id='Autofac'```.

**Comment by lukeskinner** [comment] 2016-04-02 17:33
Looking into the NuGet.Lucene.Web library in the NuGetWebApiRouteMapper class, I can see a http route which should redirect /api to /api/odata. Appending a wildcard makes it redirect all requests under /api instead of just the /api URL.

This works but I haven't confirmed yet that this doesn't break any other endpoints.

The pathPrefix variable in the code below is set to ```api/``` by default.

Current:
``` c#
 // redirect NuGet user agents from /api to /api/odata
            config.Routes.MapHttpRoute(RouteNames.Redirect.ApiFeed,
                                pathPrefix,
                                new { },
                                new { userAgent = new NuGetUserAgentConstraint() },
                                new ODataRedirectHandler(RouteNames.Packages.Feed));
```

Potential fix: 
``` c#
            // redirect NuGet user agents from /api to /api/odata
            config.Routes.MapHttpRoute(RouteNames.Redirect.ApiFeed,
                                pathPrefix + "*",
                                new { },
                                new { userAgent = new NuGetUserAgentConstraint() },
                                new ODataRedirectHandler(RouteNames.Packages.Feed));
```

**Comment by felickz** [comment] 2016-04-04 13:00
OI, lets get some Klondike usage in the VS team RC testing!

**Comment by Framnk** [comment] 2016-04-04 14:20
Anyone have any thoughts on if this is going to be possible to fix/workaround on version 1.5.1?  We haven't been able to upgrade to 2.0 yet since it is no longer possible to host Klondike except at the IIS root.

**Comment by enkafan** [comment] 2016-04-04 14:20
thanks @lukeskinner - the `/api/odata` path got me moving forward.

**Comment by CasperTDK** [comment] 2016-04-06 18:58
Confirmed @lukeskinner  api/odata works for me!

**Comment by alpaix** [comment] 2016-04-08 22:39
We (the NuGet team) have a fix for this which we will publish soon with v3.4.2.

**Closed** 2016-04-27 14:16 UTC

**Comment by ronnyek** [comment] 2016-09-29 21:42
Im running the latest release as of today of 2.2.1, visual studio enterprise 2015 update 3, and nuget plugin 3.5.0.1484. I cannot see pre-release packages using visual studio package manager. Nuget package explorer works just fine. I don't know if this is a klondike or nuget thing, but it sounds like v3.4.2 is out there and this problem still exists.
